#!/usr/bin/env python
"""Generate data/dso_catalog/emission_nebulae.yaml from the image books.

Unions the Esprit 120 + Esprit 80 + S30 emission books (dedup by canonical
name), maps each to the DSO catalog schema (catalog.py), assigns narrowband
budgets from the palette, and flags mosaic=true when the object overflows
even the S30's measured wide field (incl. the planner's 10% rim tolerance).
Consumable per-night via:
    mira emission plan --config config/<rig>.yaml
"""
import csv
from pathlib import Path

ESP = Path("output/books/esprit_emission_book/emission_book.csv")
E80 = Path("output/books/esprit80_emission_book/emission_book.csv")
S30 = Path("output/books/s30_emission_book/emission_book.csv")
OUT = Path("data/dso_catalog/emission_nebulae.yaml")

TYPE_MAP = {"HII":"HII","HII+refl":"HII","WR bubble":"WR","PN":"PN","SNR":"SNR","WR":"WR"}

def budget(pal):
    p = pal.lower()
    if "sii" in p or ("sho" in p and "hoo" not in p): return {"Ha":180,"OIII":120,"SII":120}
    if "sho" in p and "hoo" in p:                       return {"Ha":150,"OIII":150,"SII":90}
    if "ha-strong" in p or p.startswith("ha /") or p.startswith("ha+"):
        return {"Ha":210,"OIII":90}
    if "hoo" in p or "oiii" in p:                       return {"Ha":120,"OIII":180}
    return {"Ha":150,"OIII":150}

def load(p):
    return {r["qid"]: r for r in csv.DictReader(open(p, encoding="utf-8"))}

esp, e80, s30 = load(ESP), load(E80), load(S30)
names = list(esp.keys())
for src in (e80, s30):
    names += [n for n in src if n not in names]
rows = []
for n in names:
    e = esp.get(n); m = e80.get(n); s = s30.get(n); base = e or m or s
    maj, mn = float(base["maj"]), float(base["min"])
    pal = base["pal"]
    notes = []
    if e: notes.append(f"Esprit: {e['fit']}, {e.get('rot','')}".strip(", "))
    if m: notes.append(f"E80: {m['fit']}")
    if s: notes.append(f"S30: {s['fit']}")
    notes.append(base["note"])
    rows.append(dict(
        name=n, common=base["common"], typ=TYPE_MAP.get(base["typ"], "HII"),
        ra=float(base["ra"]), dec=float(base["dec"]), maj=maj, mn=mn,
        const=base["const"], pal=pal, budget=budget(pal),
        # Static flag = "mosaic on ANY rig": overflows even the S30's measured
        # 3.91x2.20deg field with the planner's 10% rim tolerance applied
        # (235'x1.1 / 132'x1.1). Per-rig single-frame fit is computed at plan
        # time from fov_deg, so the Esprit 120 correctly flags the medium
        # giants (NGC7000, Heart) that the 80 and S30 frame single-shot.
        mosaic=(maj > 258.0 or mn > 145.0),
        notes=" | ".join(x for x in notes if x)))

# emit YAML by hand (keeps formatting clean + comments)
L = ['# Emission-nebula catalog — union of the Esprit 120 + Esprit 80 + S30 Pro',
 '# image books (output/books/*_emission_book/). Auto-generated by',
 '# output/books/esprit_emission_book/make_mira_catalog.py from the',
 '# SIMBAD-resolved books. Rank per night with the emission planner:',
 '#   mira emission plan --config config/<rig>.yaml',
 '# mosaic=true flags objects that overflow even the S30\'s measured wide field',
 '# (3.91x2.20deg, 10% rim tolerance) — single-frame fit per rig is otherwise',
 '# computed at plan time from fov_deg. Schema = data/dso_catalog/sho_targets.yaml.',
 '',
 'catalog_version: "2026-06-10-emission"',
 '',
 'defaults:',
 '  gain: 100',
 '  exposure_s: 300',
 '  filters_narrowband: [Ha, OIII, SII]',
 '',
 'targets:']
for r in rows:
    bud = ", ".join(f"{k}: {v}" for k, v in r["budget"].items())
    notes = r["notes"].replace('"', "'")
    L += [f'  - name: "{r["name"]}"',
          f'    common_name: "{r["common"]}"',
          f'    object_type: {r["typ"]}',
          f'    ra_deg: {r["ra"]:.3f}',
          f'    dec_deg: {r["dec"]:.3f}',
          f'    size_arcmin: [{r["maj"]:.0f}, {r["mn"]:.0f}]',
          f'    constellation: {r["const"]}',
          f'    budget_minutes: {{{bud}}}',
          f'    mosaic: {str(r["mosaic"]).lower()}',
          f'    notes: "{notes}"']
OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote {OUT} — {len(rows)} targets ({sum(r['mosaic'] for r in rows)} mosaic-flagged)")
